spring:
  profiles:
    active: dev
    include: oauth
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    enabled: true

jwt:
  secret: fpvuvttzKZKGmQ3UoD0QpU7oSDAmCKb8X6l78RULm1Rm01R5Itcg5C8Q9me5sffF